# ISH-ApplicationRegistrationService.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/InsuranceSystemForHealth
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

# Server ports for each service
---
spring:
  config:
    activate:
      on-profile: ISH-ApplicationRegistrationService
server:
  port: 7071
ar:
  ssa-web:
    url: http://localhost:9090/ssa-web-api/find/{ssn}
  state: california

---
spring:
  config:
    activate:
      on-profile: ISH-AdminService
server:
  port: 7074
management:
  endpoint:
    env:
      enabled: true
      show-values: always
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
plan:
  module:
    messages:
      save-success: Plan is saved with id value
      save-failure: Plan is not saved with Value
      find-by-id-failure: Plan is not found
      update-success: Plan is updated
      update-failure: Plan is not found for updation
      delete-success: Plan is deleted
      delete-failure: Plan is not found for deletion
      status-change-success: Plan Status is changed
      status-change-failure: Plan is not found for status change

---
spring:
  config:
    activate:
      on-profile: ISH-BenefitIssuanceService
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
server:
  port: 7076
benefit:
  issuance:
    output-file: beneficiries_list.csv

---
spring:
  config:
    activate:
      on-profile: ISH-CorrespondenceService
  mail:
    host: smtp.gmail.com
    port: 587
    username: lakshaychaudhary2003@gmail.com
    password: your-app-password
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true
server:
  port: 7075
correspondence:
  pdf:
    output-dir: ./pdf-notices

---
spring:
  config:
    activate:
      on-profile: ISH-DataCollectionService
server:
  port: 7072

---
spring:
  config:
    activate:
      on-profile: ISH-EligibilityDeterminationService
server:
  port: 7073

---
spring:
  config:
    activate:
      on-profile: ISH-GovernmentReportService
server:
  port: 7077
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
gov-report:
  output-directory: reports/government
  report-types:
    - eligibility
    - benefit
    - application
    - data-collection
  formats:
    - pdf
    - excel
  default-format: pdf

---
spring:
  config:
    activate:
      on-profile: ISH-UserMgmtService
  mail:
    host: smtp.gmail.com
    port: 587
    username: lakshaychaudhary2003@gmail.com
    password: your-app-password
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true
server:
  port: 4041
mailbody:
  registeruser:
    location: src/main/java/in/lakshay/service/user_registration_body.txt
  recoverpwd:
    location: src/main/java/in/lakshay/service/recover_pwd_body.txt

---
spring:
  config:
    activate:
      on-profile: ISH-CloudAPIGateway
server:
  port: 7777
  cloud:
    gateway:
      routes:
      - id: ISH-AdminService
        predicates:
        - Path=/plan-api/**
        uri: lb://ISH-AdminService
      - id: ISH-ApplicationRegistrationService
        predicates:
        - Path=/CitizenAR-api/**
        uri: lb://ISH-ApplicationRegistrationService
      - id: ISH-BenefitIssuanceService
        predicates:
        - Path=/bi-api/**
        uri: lb://ISH-BenefitIssuanceService
      - id: ISH-CorrespondenceService
        predicates:
        - Path=/co-triggers-api/**
        uri: lb://ISH-CorrespondenceService
      - id: ISH-DataCollectionService
        predicates:
        - Path=/dc-api/**
        uri: lb://ISH-DataCollectionService
      - id: ISH-EligibilityDeterminationService
        predicates:
        - Path=/ed-api/**
        uri: lb://ISH-EligibilityDeterminationService
      - id: ISH-GovernmentReportService
        predicates:
        - Path=/report-api/government/**
        uri: lb://ISH-GovernmentReportService
      - id: ISH-UserMgmtService
        predicates:
        - Path=/user-api/**
        uri: lb://ISH-UserMgmtService
